# Generated by Django 3.2.9 on 2022-07-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('G', 'Женский')], default='', max_length=1, verbose_name='Пол'),
        ),
    ]
