# Generated by Django 3.2.9 on 2022-08-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20220730_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='lastname',
            field=models.CharField(max_length=40, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='number',
            field=models.CharField(max_length=11, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='patronymic',
            field=models.CharField(max_length=40, verbose_name='Отчетсво'),
        ),
    ]
