# Generated by Django 3.2.9 on 2022-08-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20220801_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='LastAuthDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
