# Generated by Django 3.2.9 on 2022-08-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_customuser_lastauthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='right',
            name='usertype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.type', verbose_name='Тип пользователя'),
        ),
    ]
