# Generated by Django 3.2.9 on 2022-07-04 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(default='', max_length=250, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='files',
            field=models.FileField(default=None, upload_to='files/', verbose_name='Файлы'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('EX', 'В ожидании'), ('AC', 'В производстве'), ('MD', 'Сделан'), ('NI', 'Требует доработки')], default='EX', max_length=2, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='tasktype',
            field=models.CharField(choices=[('ER', 'Ошибка'), ('UP', 'Обновить'), ('RE', 'Рекомендация'), ('ID', 'Идея')], default='UP', max_length=2, verbose_name='Тип задачи'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
