# Generated by Django 3.2.9 on 2022-07-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20220706_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytask',
            name='change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historytask',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task', to='mainapp.task', verbose_name='Задача'),
        ),
    ]
