# Generated by Django 3.2.9 on 2022-07-06 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_auto_20220706_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=100, verbose_name='Текст')),
                ('files', models.FileField(blank=True, default=None, upload_to='comment_files/', verbose_name='Прикрепленные файлы')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='сomments', to='mainapp.task', verbose_name='Задача')),
            ],
        ),
        migrations.DeleteModel(
            name='Commentary',
        ),
    ]
