# Generated by Django 3.2.9 on 2022-07-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color_status',
            field=models.CharField(choices=[('GR', 'Зеленый'), ('RD', 'Красный'), ('YE', 'Желтый'), ('DR', 'Серый')], default='DR', max_length=2, verbose_name='Цвет статуса'),
        ),
    ]
