# Generated by Django 3.2.9 on 2022-07-16 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20220716_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип заявки')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='tasktype',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.tasktype', verbose_name='Тип заявки'),
        ),
    ]
