# Generated by Django 3.2.9 on 2022-07-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edit_directory', '0001_initial'),
        ('mainapp', '0012_auto_20220716_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='edit_directory.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasktype',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='edit_directory.tasktype', verbose_name='Тип заявки'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
