# Generated by Django 3.2.9 on 2022-08-17 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edit_directory', '0001_initial'),
        ('mainapp', '0017_alter_task_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default='В ожидании', on_delete=django.db.models.deletion.DO_NOTHING, to='edit_directory.status', verbose_name='Статус'),
        ),
    ]
