# Generated by Django 3.2.9 on 2022-08-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_comment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=None, max_length=100, verbose_name='Заголовок'),
        ),
    ]
