# Generated by Django 3.2.9 on 2022-07-16 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mytasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mytask', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
