# Generated by Django 3.2.9 on 2022-07-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Название статуса')),
                ('comment_is_active', models.BooleanField(default=False, verbose_name='Возможность комментировать')),
                ('color_status', models.CharField(choices=[('GR', 'Зеленый'), ('RD', 'Красный'), ('YE', 'Желтый'), ('DR', 'Серый')], default='DR', max_length=2, verbose_name='Цвет статуса')),
                ('image_status', models.ImageField(blank=True, default=None, upload_to='image_status/', verbose_name='Иконка статуса')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип заявки')),
            ],
        ),
    ]
