# Generated by Django 3.2.9 on 2023-05-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_directory', '0005_alter_status_palette_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color_status',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Цвет статуса'),
        ),
    ]
