# Generated by Django 3.2.9 on 2023-05-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit_directory', '0006_alter_status_color_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='palette_status',
        ),
    ]
